### ISSUE TITLE
Need more cleanup to demo app 

### ISSUE THREAD

**Issue by srbala** [pf4j/pf4j-web#5]
Demo app config needs use dynamc path dedection instead of hard coded path in web.xml

**Comment by srbala** [comment]
Following may be the possible list to complete this issue ...

- [x] Complete code format, #7 
- [x] Rename folder pf4j-web-demo to demo, reorg as necessary to match pattern with other organisation projects, #8
- [x] Setup clean up scripts for generated plugins and folder, remove from git repo, #9
- [x] Update readme for demo, #10
- [ ] Add common documents for better project management, CODE_OF_CONDUCT, CHANGE LOG, CONTRIBUTING and ISSUE_TEMPLATE etc, #11
- [ ] Update pom.xml for remote publish, #12
